example <- matrix(c(1,2,3,4,5,6,7,8), nrow = 4, ncol = 2)
install.packages(c("ggplot2","devtools","lme4"))
library(ggplot2)
old.packages()
update.packages()
remove.packages("ggplot2")
install.packages("ggplot2")
help(package = "ggplot2")
browseVignettes("ggplot2")
sessionInfo()
